### ISSUE TITLE
Migrate files in less to sass

### ISSUE THREAD

**Issue by JonatanSalas** [redux-autoform/redux-autoform-bootstrap-ui#1]
This issue was in redux-autoform but since we have moved all the bootstrap ui to here, I have to open it to mark as a possible change.

**Comment by andrerpena** [comment]
This is important because Bootstrap 4 is going SaSS

**Comment by JonatanSalas** [comment]
@andrerpena we will take care about this! :smile:

**Comment by danigomez** [comment]
Closed according #11
