### ISSUE TITLE
Add support for Async items loading from API

### ISSUE THREAD

**Issue by JonatanSalas** [redux-autoform/redux-autoform-bootstrap-ui#15]
Add support for Async items loading from API on Select and LookUp components

**Comment by JonatanSalas** [comment]
This needs to be tested, so I will create an api in demo to expose a json data. Now if you grab in layout.json the following: 

``` json
"component": "Select",
"options": {
      "url": "/api/countries",
      "label": "label",
      "value": "value"
}
```

The select and lookup components should be able to get data from a webservice. We should add the ability to have options and array too, so we can merge the arrays into one.

**Comment by danigomez** [comment]
I was also thinking that we can add in the future in the url option the dataType that the service will respond ! :stuck_out_tongue:

**Comment by andrerpena** [comment]
Jony you're the hero... thanks for that. 

I didn't quite understand this part: 

```
"component": "Select",
"options": {
      "url": "/api/countries",
      "label": "label",
      "value": "value"
}
```

How are you treating this? I suppose you did it this way: If you pass an array, then it's synchronous. If you pass an object, then it's a URL definition.  How about asynchronous options? I was thinking that being able to receive a function that returns a promise would also be a good option.

Thanks anyway!

**Comment by andrerpena** [comment]
Also, remember to add default values for label and text so they wouldn't be required.

**Comment by andrerpena** [comment]
Actually.. we could have multiple possible **types** for `options:
- Array: Default way.
- String: This would be the URL. The default **label** and **value** are considered.
- Object: The object would contian `url`, `label` and `value`. The last 2 are optional as the defaults would be considered.
- Function: A function that returns a promise that resolves the options

What do you guys think? I'm not disqualying your work Jony, that's an amazing progress.. I'm just discussing possibilities for the future :)

**Comment by JonatanSalas** [comment]
@andrerpena there's no trouble, we should work a bit more on this, but I think what you say sounds really good! I will take a look on how to achieve this.

**Comment by JonatanSalas** [comment]
I will close it for now since it's done the first part, then we could make some improvements over this components, but for now I want to let them as they are, and focus a little bit on testing.
