### ISSUE TITLE
Add documentation for Lookup and Select from API

### ISSUE THREAD

**Issue by JonatanSalas** [redux-autoform/redux-autoform-bootstrap-ui#22]

**Comment by andrerpena** [comment]
I think the only metadata that is specific to Lookup and Select is the `options`, which is described in the docs already. See: https://github.com/redux-autoform/redux-autoform-bootstrap-ui#components

**Comment by JonatanSalas** [comment]
@andrerpena the **url** in options is not specified!

**Comment by andrerpena** [comment]
I'm sorry. I didn't remember this feature was even implemented. =)

Em 15 de ago de 2016 13:45, "Jonatan E. Salas" notifications@github.com
escreveu:

**Comment by JonatanSalas** [comment]
@andrerpena you can fill select from a url and lookup too!

**Comment by andrerpena** [comment]
Oh my god you are right

**Comment by andrerpena** [comment]
I'm taking this now

**Comment by JonatanSalas** [comment]
@andrerpena good! :smile:

**Comment by JonatanSalas** [comment]
@andrerpena check the demo preset for select and lookup! There are some examples on how to use it! :smile:

**Comment by andrerpena** [comment]
Thanks @JonatanSalas . I'll take this today

**Comment by JonatanSalas** [comment]
@andrerpena! Great! Thanks to you! :)

**Comment by andrerpena** [comment]
Done
