### ISSUE TITLE
Refactor tabs to be a separate Group component

### ISSUE THREAD

**Issue by andrerpena** [redux-autoform/redux-autoform-bootstrap-ui#24]
@JonatanSalas I really really appreciate the effort you've put into this. I just don't agree with the way you did it :smiley_cat: 

RAF is supposed to support multiple field and group components. Tabs should be a group. There should be 2 components for groups now: `Group.js` and `TabGroup.js`. This is the scalable way to go.

Don't worry. Thank you again and I'll make the required refactoring.

**Comment by JonatanSalas** [comment]
There is no trouble. If you got this after wednesday.. or let me help you. Because I need to use it! :/

**Comment by andrerpena** [comment]
I'll try to fix this tomorrow.

**Comment by JonatanSalas** [comment]
Thank you very much! :)

**Comment by JonatanSalas** [comment]
@andrerpena I have made a refactor to it, when you can, take a look. I will add the demo presets for TabGroup to see it working properly.

**Comment by JonatanSalas** [comment]
This is already done! I will submit a PR
