### ISSUE TITLE
Fix tab styles

### ISSUE THREAD

**Issue by andrerpena** [redux-autoform/redux-autoform-bootstrap-ui#26]
@JonatanSalas , I appreciate very much your effort for making this. I'm just creating this issue because it's not production grade. See the screenshot:

![tabs](https://i.imgur.com/X7FLWkM.png)

Problems:
- [X] At first, no tab is selected (bug)
- [X] The group header is repeated (in the tab and inside the tab) (bug)
- [X] The selected style (darker) is not right.
- [X] The tab header is wider than it should (no bleeding/spacing in the sides).
- [X] Add a marginTop for headLess Group
- [x] Add warning on Tab when some field is Required

If you don't want to take this, I'll take this. Don't worry. It's just here for science.

**Comment by andrerpena** [comment]
For the repeated header, we'll unfortunately have to create a headless group. **Do not take this without talking to me first, please**.

**Comment by JonatanSalas** [comment]
I made a basic approach with the only idea in mind to show the tabs, because that was a requirement I need. I know that I requires more work on it, and what you say it's true!

**Comment by andrerpena** [comment]
@JonatanSalas Thanks.. You did a good job. Just needs some tuning ;)

**Comment by JonatanSalas** [comment]
@andrerpena you are welcome, when I started to do it, I have some doubts, so I made the tabs in a way I clear my doubts, and works. 

It's hard to do something well when you have pression :/

**Comment by JonatanSalas** [comment]
@andrerpena I will take this the next week possibly!

**Comment by andrerpena** [comment]
@JonatanSalas Thank you!

**Comment by JonatanSalas** [comment]
The problems I have solved: 
- [X] At first, no tab is selected (bug)
- [X] The selected style (darker) is not right.
- [X] The tab header is wider than it should (no bleeding/spacing in the sides).

The only thing that rest: 
- [x] The group header is repeated (in the tab and inside the tab) (bug)

This how actually looks the tabs after the fix I made. What's you opinion? 

![captura de pantalla de 2016-08-13 13-36-00](https://cloud.githubusercontent.com/assets/7697196/17644368/eb51dd3c-615a-11e6-96e6-01431f56d206.png)

**Comment by JonatanSalas** [comment]
@andrerpena when you can, I would like to make the headless group with your help!

**Comment by andrerpena** [comment]
You did an excellent job. I'll take care of the headless group. I think the simplest solution is to add a prop to group called "headless" that defaults to false. Then, inside the TabsGroup, we pass the headless prop as true when creating the inner group. I'll take care of it. Thank you very much for your effort.

**Comment by JonatanSalas** [comment]
@andrerpena thanks! :) 
OK, I have assigned the rest to you. So I will keep this open until you do this! :smile:

**Comment by JonatanSalas** [comment]
HeadLess is now supported! 

All the issues are fixed: 
- [X] At first, no tab is selected (bug)
- [X] The selected style (darker) is not right.
- [X] The tab header is wider than it should (no bleeding/spacing in the sides).
- [X] The group header is repeated (in the tab and inside the tab) (bug)

![captura de pantalla de 2016-08-13 19-27-33](https://cloud.githubusercontent.com/assets/7697196/17645971/1b116c46-618c-11e6-8e95-7ca6bad3a0c0.png)

**Comment by JonatanSalas** [comment]
When you run the demo you will see this error. This is because the prop justified in react-bootstrap is passed downside, so It throws this error, but this property is valid. If you delete this prop from TabGroup you will see the Tabs in a bad form. 

![captura de pantalla de 2016-08-13 19-40-43](https://cloud.githubusercontent.com/assets/7697196/17646009/f47acdd2-618d-11e6-8845-1b6c5f283ac5.png)

**Comment by JonatanSalas** [comment]
@andrerpena well.. I have finished :smile:

**Comment by andrerpena** [comment]
@JonatanSalas Excellent job!

**Comment by JonatanSalas** [comment]
@andrerpena rest that you approbe the PR! :)

**Comment by andrerpena** [comment]
That's exactly what I was thinking :)

**Comment by JonatanSalas** [comment]
@andrerpena We are on the same channel!! :smile:

**Comment by JonatanSalas** [comment]
I will keep this open because I want to add support for something else, when a field is required or has a validation error and you make a submit, It would be good if the tab color change to red to mark you where are some errors...

what's your opinion about this?

**Comment by andrerpena** [comment]
That makes sense. I created a branch somewhere called `required-star` because I wanted to display a star (asterisk) when a field is required. This is not directly related to what you're proposing but anyway, I agree to you.

**Comment by JonatanSalas** [comment]
@andrerpena good, I have see it! Well, I will work on this :smile: and after this, I will close this issue.

**Comment by JonatanSalas** [comment]
This is currently supported
