### ISSUE TITLE
Jonatas, don't forget to change the demo URL

### ISSUE THREAD

**Issue by andrerpena** [redux-autoform/redux-autoform-bootstrap-ui#3]
@JonatanSalas , in this URL http://redux-autoform.github.io/redux-autoform/demo.html the `/redux-autoform/demo.html` is part is used by the route. That means that, because you changed the name of the project, the route should be changed accordingly, ok? :smile:

**Comment by JonatanSalas** [comment]
I will take care about this @andrerpena! Thanks for the remember!

**Comment by andrerpena** [comment]
I did this already

**Comment by JonatanSalas** [comment]
Thank you very much andré! Great work! 😃
