### ISSUE TITLE
Remove the "languages" API for the Lookup component

### ISSUE THREAD

**Issue by andrerpena** [redux-autoform/redux-autoform-bootstrap-ui#30]
I'll replace it with a public API so I can publish it

**Comment by JonatanSalas** [comment]
The trouble with this, it's that we must map the content from the API you add to an array of type: 
[{ value: "", label: "" }]

So we need to modify the Select and Lookup components

**Comment by andrerpena** [comment]
Worry not, young Jonatan.. I have solved it.

**Comment by andrerpena** [comment]
I'll commit shortly

**Comment by JonatanSalas** [comment]
@andrerpena geniuuus!!

**Comment by andrerpena** [comment]
Done
