### ISSUE TITLE
Add password type to input

### ISSUE THREAD

**Issue by danigomez** [redux-autoform/redux-autoform-bootstrap-ui#33]

**Comment by andrerpena** [comment]
I'll get this one now. Izzzy.

**Comment by JonatanSalas** [comment]
@andrerpena thank you! :)

**Comment by danigomez** [comment]
Greeaaaaaat :smile:

**Comment by andrerpena** [comment]
At first I wasn't sure if password was a data-type, a component or just an additional metadata for string fields.

I decided it was a component. Added a demo already (which I didn't publish).

Done.
