### ISSUE TITLE
Is the demo currently publishable?

### ISSUE THREAD

**Issue by andrerpena** [redux-autoform/redux-autoform-bootstrap-ui#34]
@JonatanSalas and @danigomez , as you probably realized, I removed the language API from the demo and replaced it with a public GitHub API so we could make the demo more publishable.. I mean.. reduce the need to actually have a server running.

What about the file upload? If I publish the demo right now on GH, will it work? How are we currently dealing with the upload problem?

Thank you.

**Comment by JonatanSalas** [comment]
@andrerpena actually the file upload needs a service for succesful upload, but we can mock the upload, because server detail could be in documentation.

**Comment by andrerpena** [comment]
I agree with this mocking approach. I'm just worried because I don't know
if I can publish the demo anymore. Do we have the demo in a state that it
can be published right now? Otherwise this should be a priority

Em 19 de ago de 2016 10:09, "Jonatan E. Salas" notifications@github.com
escreveu:

**Comment by JonatanSalas** [comment]
@andrerpena Yes, it can be published. The file upload will work, you will see the files been added when drag and drop and all the stuff, but you can submit an upload. That's the only thing.

**Comment by andrerpena** [comment]
*you can't. Ok.. That's perfect! Thank you

**Comment by JonatanSalas** [comment]
you can't haha thanks for the correction!
