### ISSUE TITLE
Refactor demo with a new folder structure

### ISSUE THREAD

**Issue by JonatanSalas** [redux-autoform/redux-autoform-bootstrap-ui#41]
Actually the demo folder structure it's a little bit tricky. So I open this task to perform a refactor of the demo in order to be more easy to understand.

**Comment by andrerpena** [comment]
what exactly do you mean by easier to understand? What do you plan to change?

**Comment by JonatanSalas** [comment]
I will organize it in the same way I have organized the demo in Material-UI, look: 

![captura de pantalla de 2016-09-04 22-19-54](https://cloud.githubusercontent.com/assets/7697196/18235170/e97af5da-72ed-11e6-8863-95f656c89ae2.png)

Do you agree?

**Comment by andrerpena** [comment]
Yes it looks good

**Comment by andrerpena** [comment]
I was going to make some changes in the demo structure, that's why I came here to see this thread. I'm leaving things as they are now then, as you're looking into this already. Thanks.

**Comment by JonatanSalas** [comment]
Today at night I will do this refactor so you can keep working properly with it :)

**Comment by JonatanSalas** [comment]
@andrerpena this is done! :smile: You can check it!
