### ISSUE TITLE
Create the EntityContainer component

### ISSUE THREAD

**Issue by andrerpena** [redux-autoform/redux-autoform-bootstrap-ui#48]

**Comment by JonatanSalas** [comment]
The EntityContainer component should be in the Root by default, dont you think? Because the Entity support it's something that comes with Autoform Core.

**Comment by JonatanSalas** [comment]
Another thing I notice it's that the EntityContainer code it's similar to group

**Comment by andrerpena** [comment]
I think the EntityContainer should be sibling to ArrayContainer and other field components I think. And yes, they're similar.
