### ISSUE TITLE
I'm bringing the demo back to the master branch of redux-autoform-bootstrap-ui so I can be productive

### ISSUE THREAD

**Issue by andrerpena** [redux-autoform/redux-autoform-bootstrap-ui#5]
@JonatanSalas and @danigomez , I just found a bug on the CheckBox component and now it's extremely hard to debug, because I was used to update the component on Redux-Autoform and see the changes immediately take place on the Demo because of hot-reloading.

Now the UI is separate, which I agree 100%, but the demo should be together with the UI, so I can do things we way I was used to. I mean, if I change the CheckBox, I have to see the results fast. The way it's structured now, the UI project is separate from the demo (which is in another branch). Unfurtunely this is impractical to me. I know @JonatanSalas uses `carte-blanche` but that doesn't work on Windows.

I really appreciate the work you 2 are putting into this and you've being doing an amazing job, but I have to desagree with a separate demo, so I'm moving the demo back to this project now (no separate branch for the demo). I hope you don't mind or suggest something that brings back my productivity.

Thank you!

**Comment by andrerpena** [comment]
This is done except that I didn't publish the demo to gh-pages yet. Once I've done it I'll close this.,

**Comment by JonatanSalas** [comment]
@andrerpena gh-pages it's now publish, not? So I will close this issue!

**Comment by andrerpena** [comment]
Yes it is, thank you
