### ISSUE TITLE
Bootstrap UI demo broke after select some presets from drop down.

### ISSUE THREAD

**Issue by kangkai1980** [redux-autoform/redux-autoform-bootstrap-ui#51]
The related presets are:
**"Schema types - Simple"**
**"Components - DateTimePicker"**
**"Components - Number"**

When select the mentioned items from preset dropdown, the AutoForm on the right will not display the layout and stop responing. This behavior was caused by the page cannot recover from exception thrown from line 73 of ComponentFactory.js, redux-autoform-utils. When select a new preset, there will be an error in console: "Uncaught TypeError: Cannot read property 'replaceChild' of null":

![autoformerror](https://cloud.githubusercontent.com/assets/20306166/18982786/37e45a7c-871b-11e6-97f8-25f526ff7e36.png)

Here are the root cause of the exceptions:
- The first two ("Schema types - Simple" and "Components - DateTimePicker") were caused by using DateTimePicker component from react-widgets without a localizer.
  I have a fix propose, but I don't know if the code is in the right place:

Replace line 3 in 'src\index.js' with following code:

```
import Moment from 'moment';
import momentLocalizer from 'react-widgets/lib/localizers/moment';

momentLocalizer(Moment);
```
- The last one ("Components - Number") is caused by the lack of a 'Number' register in BootstrapFactory.js

**Comment by JonatanSalas** [comment]
Hey, thank you for this issue report, I will check today the demo source code, and make those changes to fix this!

**Comment by JonatanSalas** [comment]
@kangkai1980 excuse for the late response, but I have been with tons of work. I have solved the issues that you have marked, so in the next update of the demo, maybe tomorrow I will upload the update. You could see this fixed!

**Comment by kangkai1980** [comment]
I don't know why the page at 
[https://redux-autoform.github.io/redux-autoform-bootstrap-ui/demo.html](url)
is not fixed. But I can confirm that after I pulled the code from github and run "npm start", it works properly on my localhost:4000

**Comment by JonatanSalas** [comment]
I havent uploaded yet the fixed demo, sorry! My bad!
